/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Grassy Meadow',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 500,
      obstacleCount: 5,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Rolling Hills',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 75,
      targetScore: 750,
      obstacleCount: 7,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 10,
      backgroundTheme: 'rolling_hills',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Enchanted Forest',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.4,
      timeLimitSeconds: 90,
      targetScore: 1000,
      obstacleCount: 10,
      obstacleSpeed: 0,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'enchanted_forest',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Cloudy Peaks',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 120,
      targetScore: 1500,
      obstacleCount: 12,
      obstacleSpeed: 0,
      collectibleCount: 25,
      collectibleValue: 10,
      backgroundTheme: 'cloudy_peaks',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Lava Cavern',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 150,
      targetScore: 2000,
      obstacleCount: 15,
      obstacleSpeed: 0,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'lava_cavern',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Frozen Tundra',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 180,
      targetScore: 2500,
      obstacleCount: 18,
      obstacleSpeed: 0,
      collectibleCount: 35,
      collectibleValue: 10,
      backgroundTheme: 'frozen_tundra',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Neon City',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 210,
      targetScore: 3000,
      obstacleCount: 20,
      obstacleSpeed: 0,
      collectibleCount: 40,
      collectibleValue: 10,
      backgroundTheme: 'neon_city',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Haunted Manor',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 240,
      targetScore: 3500,
      obstacleCount: 22,
      obstacleSpeed: 0,
      collectibleCount: 45,
      collectibleValue: 10,
      backgroundTheme: 'haunted_manor',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Futuristic Skyway',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 270,
      targetScore: 4000,
      obstacleCount: 25,
      obstacleSpeed: 0,
      collectibleCount: 50,
      collectibleValue: 10,
      backgroundTheme: 'futuristic_skyway',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Cosmic Abyss',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 300,
      targetScore: 5000,
      obstacleCount: 30,
      obstacleSpeed: 0,
      collectibleCount: 60,
      collectibleValue: 10,
      backgroundTheme: 'cosmic_abyss',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
